### ISSUE TITLE
Fetch resources concurrently using goroutines

### ISSUE THREAD

**Issue by Azanul** [tailwarden/komiser#1014]
**Is your feature request related to a problem? Please describe.**
Komiser fetches all resources sequentially. Since the resources/accounts are independent, they can be fetched concurrently.

**Describe the solution you'd like**
Use goroutines to fetch resources concurrently.

**Additional context**
This discussion is a continuation of the same from #1006 

@jakepage91 @AvineshTripathi

**Comment by Azanul** [comment]
I have a couple options in my mind to choose from
1. Pool the functions fetching the resources
2. Pool the accounts for which resources are being fetched

In both of these cases, the pool is initialized at application level before any fetching is started.

### Pool the functions fetching the resources

1. We go through accounts/providers sequentially.
2. We fan-in all the `FetchDataFunction`s through channels to the pool of goroutines.

### Pool the accounts for which resources are being fetched

1. We fan-in all the `provider`s through channels to the pool of goroutines. 
2. Each resource in that provider is then fetched as it does now i.e., sequentially.

### Example

```go
func main() {
    // Create a channel to receive tasks.
    tasks := make(chan func(int, int), 10)

    var wg sync.WaitGroup

    // Start worker goroutines.
    numWorkers := 3
    for i := 0; i < numWorkers; i++ {
        wg.Add(1)
        go worker(i, tasks, &wg)
    }

    // Add tasks to the task channel.
    for i := 0; i < 10; i++ {
        tasks <- func(a, b int) {
            c := api.fetch(a, b)
            db.save(c)
        }
    }

    // Close the task channel to signal that no more tasks will be added.
    close(tasks)

    // Wait for all workers to finish.
    wg.Wait()
}

func worker(id int, tasks <-chan func(int, int), wg *sync.WaitGroup) {
    defer wg.Done()

    for task := range tasks {
        task()
    }
}
```

**Comment by AvineshTripathi** [comment]
I think we should go for pooling the functions and not accounts as at individual provider level we already do go routines however as the number of providers is definately not something that will grow enormously we can keep it as it is. Ref: https://github.com/tailwarden/komiser/blob/develop/internal/internal.go#L339

For individual fetching resource we can have something

Also I have a very much general idea/ random thought that how about we create a worker pool functionality and pass the func to individual provider i.e here https://github.com/tailwarden/komiser/blob/develop/internal/internal.go#L291 
Reason: we can create a general func that may or maynot be worker pool(more like abstraction) so that incase there are some providers for which having a worker pool would be uncessary stress giving so at that time we can keep things like now and will then have an architecture where some providers will run with worker pool while some would not but ensuring the structure is common for all. Let me know if I confused you more!

**Comment by Azanul** [comment]
> I think we should go for pooling the functions and not accounts as at individual provider level we already do go routines however as the number of providers is definately not something that will grow enormously we can keep it as it is. Ref: https://github.com/tailwarden/komiser/blob/develop/internal/internal.go#L339
>

I agree

> Also I have a very much general idea/ random thought that how about we create a worker pool functionality and pass the func to individual provider i.e here https://github.com/tailwarden/komiser/blob/develop/internal/internal.go#L291 Reason: we can create a general func that may or maynot be worker pool(more like abstraction) so that incase there are some providers for which having a worker pool would be uncessary stress giving so at that time we can keep things like now and will then have an architecture where some providers will run with worker pool while some would not but ensuring the structure is common for all. Let me know if I confused you more!

Passing the func to individual provider sounds like adding tech debt. If we find out that we get better performance by excluding some functions from the pool, then we simply won't send them to the pool.
Since most of the resource functions already have the same signature, implementing the worker pool on an application level is easy.

**Comment by AvineshTripathi** [comment]
> Passing the func to individual provider sounds like adding tech debt. If we find out that we get better performance by excluding some functions from the pool, then we simply won't send them to the pool. Since most of the resource functions already have the same signature, implementing the worker pool on an application level is easy.

I agree to this, lets start slow then create a general worker func that could be used in providers fetching and get our fetching speed increase
