### ISSUE TITLE
Estimate cost of GCP VM Instances

### ISSUE THREAD

**Issue by eneskaya** [tailwarden/komiser#652]
The cost estimation of VM Instances can be theoretically accomplished via the [Cloud Billing Catalog API](https://cloud.google.com/billing/v1/how-tos/catalog-api). However, the API is not very convenient to use, as as of now there is no way to filter through the [SKUs](https://cloud.google.com/skus/sku-groups) to find pricing details for a given instance. One would have to parse the description of the APIs to find and match the pricing details for CPU, RAM and Disk for one instance. Doing that in a performant manner is even harder. 

Open for ideas and PRs on how to tackle this issue.

**Comment by ShubhamPalriwala** [comment]
On top of my mind, we can fetch the common catalogues/configurations and write an equation/algorithm (not too complex) that gives the users a rough estimate of their instances. 
Pros:
- Reduces API calls and latency

Cons:
- Needs to be maintained
- Will not be exactly accurate

**Comment by PumpkinSeed** [comment]
I started to investigate this estimation and found out that the `computepb.Instance` does NOT have any valuable information for machine types/size/etc. Do you have any idea whether it has and endpoint or function which can give detailed information about the machine running under the instance?

Regarding to the Catalog API, the main problem that it's using API key. I only see two options, one that the user of komiser creating an API key and passing it in the config.toml, or the komiser itself creates an API key. But both solution isn't acceptable for UX, because if the komiser creates it (if it has the permission to create one), than the user can forgot it (even if it's in the documentation the user won't read it) and it is vulnerable since there is a dangling API key. The other one where the user creates it, so it makes harder to use the tool. 

Also the Catalog API's responses can be cached locally in memory, so this will reduce the number of API calls.

**Comment by PumpkinSeed** [comment]
Actually I was dump and missed the instance.MachineType, so we can do a cost calculation based on that value. It will fit all of the needs for built-in machine types. I don't really have anything for custom machines, but once I finished the built-in, I will create a custom image and test with it as well.

Also I found this for built-in machine type's pricing (it is from [here](https://cloud.google.com/compute/all-pricing#general_purpose)): https://www.gstatic.com/cloud-site-ux/pricing/data/gcp-compute.json

**Comment by mlabouardy** [comment]
> Actually I was dump and missed the instance.MachineType, so we can do a cost calculation based on that value. It will fit all of the needs for built-in machine types. I don't really have anything for custom machines, but once I finished the built-in, I will create a custom image and test with it as well.
> 
> Also I found this for built-in machine type's pricing: https://cloud.google.com/compute/all-pricing#general_purpose, so it would be nice to fetch this data somehow.
> 
> Raw JSON endpoint for all pricing: https://www.gstatic.com/cloud-site-ux/pricing/data/gcp-compute.json

that's a great idea of using the instance type for the calculation. If you've a draft PR, would love to give a hand on it :)

**Comment by PumpkinSeed** [comment]
I started to work on it, if I have a solution which at least count the price (not on a proper way), I will create a draft PR.

**Comment by PumpkinSeed** [comment]
I created a repository which parses the `gcp-compute.json`. [PumpkinSeed/gcpcomputepricing](https://github.com/PumpkinSeed/gcpcomputepricing), so this will have proper exported functions for that, and tested for [these prices](https://cloud.google.com/compute/all-pricing). I already created the E2 machine types and there is an example usage: 

```go
pricing, err := gcpcomputepricing.Fetch()
// err handle

hourlyRate, err := gcpcomputepricing.Get(gcpcomputepricing.E2Standard2, pricing, Opts{
	Type:   gcpcomputepricing.OnDemand,
	Region: "us-west1",
})
// err handle
```

It will able to handle custom machines as well. (It took me a while to generate these structs, because it's a huge JSON.)

What do you guys think?
