### ISSUE TITLE
Restore OVH as a provider

### ISSUE THREAD

**Issue by krismas** [tailwarden/komiser#912]
**Describe the solution you'd like**
It would be really nice to have - again - the support of OVH as a provider. Is this possible? Is it in your roadmap?

**Comment by mlabouardy** [comment]
Hey @krismas that's definitely in the roadmap. We're also looking for contributors, if you want to cover OVH, we have got a quick [video](https://www.youtube.com/watch?v=Vn5uc2elcVg) to help you get started :)

**Comment by krismas** [comment]
Many thanks for your feedback. Unfortunately, we don't yet have enough skills in Go to contribute!

**Comment by Azanul** [comment]
May I take this up?

**Comment by mlabouardy** [comment]
> May I take this up?

all yours :)

**Comment by jakepage91** [comment]
Hey there @krismas , @Azanul the latest Komiser maintainer has taken the ticket on. Feel free to join the Discord community (https://discord.tailwarden.com) so you can be notified when the provider is available and it'll also be the best way to get your feedback, since we don't have too many OVH users at the moment. Your input could be super valuable!

**Comment by AllieMendes** [comment]
Hey @Azanul! I've added the OVH cloud provider logo on the Design System, if you could add it to Storybook and update it on the platform that would be great (I'll tag you on the Design System)
