### ISSUE TITLE
Retroactively backfilling cost data 

### ISSUE THREAD

**Issue by SebastienMelki** [tailwarden/komiser#929]
I just started using komiser, but it's showing all of the months cost into a single day. As if I had spent a whole months in a single day. Is there a way to make komiser fill its databases from historical data? For example can I see 6 months back? Or will komiser only start gathering data from the day it was enabled on a certain account?

**Comment by jakepage91** [comment]
Hey there @SebastienMelki I do apologize for the delay in responding to your issue here. 
To answer your questions, yeah, Komiser only starts gathering data from the time it was enabled on the account. Cost overall on Komiser is still a little bit spotty since not all cost coverage is the same across all cloud providers and at the moment we are only just calculating the cost using the public price per resource information provided by the cloud providers, but this does not account for discounts or RI savings you might have applied to you account. That is why for now we are planning on removing our cost coverage from the majority of the cloud providers (except Civo and K8s) until we can find a more comprehensive and robust solution for delivering cost insights. In the meantime feel free to use Tailwarden (free for 14 days) since it does a much better job at offering granular cost insights (currently for AWS and GCP)
